apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: demo-prod
  namespace: kargo-demo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: demo
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - as: deploy-repo
          uses: git-clone
          config:
            repoURL: https://github.com/jonas-werner/kargo-argocd-lab-demo-deploy.git
            checkout:
              - branch: main
                create: false
                path: git-demo-deploy
        # Update the deploy repo's desired state (classic GitOps flow).
        # ArgoCD will notice the commit and sync.
        - uses: yaml-update
          config:
            path: git-demo-deploy/apps/demo/overlays/prod/kustomization.yaml
            updates:
              - key: images[0].newTag
                value: ${{imageFrom("ghcr.io/jonas-werner/kargo-argocd-lab-demo-app").Tag}}
        - uses: git-commit
          config:
            path: git-demo-deploy
            author:
              name: Kargo
              email: kargo@example.invalid
            message: |-
              deploy(demo): promote demo-prod

              stage:       demo-prod
              image:       ghcr.io/jonas-werner/kargo-argocd-lab-demo-app:${{imageFrom("ghcr.io/jonas-werner/kargo-argocd-lab-demo-app").Tag}}
        - uses: git-push
          config:
            path: git-demo-deploy
            targetBranch: main


