apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo
  namespace: kargo-demo
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    # CoreWeave-style pattern (aligned with sa-argo-deploy):
    # - Warehouse detects new git commits in the deploy repo (Freight)
    # - Promotion pins ArgoCD's desired revision to that commit SHA
    - git:
        repoURL: https://github.com/jonas-werner/kargo-argocd-lab-demo-deploy.git
        branch: main
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 20
        includePaths:
          - apps/demo


