apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo
  namespace: kargo-demo
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    # This is the "classic" Kargo pattern:
    # - CI publishes a new image tag (Freight)
    # - Kargo detects it
    # - Promotion updates the deploy repo to reference that tag
    - image:
        repoURL: ghcr.io/jonas-werner/kargo-argocd-lab-demo-app
        # Only treat semver tags as eligible Freight.
        # You can loosen/tighten this later (e.g., include prereleases).
        semverConstraint: ">=0.0.0"


