apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo
  namespace: kargo-demo
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    - image:
        repoURL: ghcr.io/jonas-werner/kargo-argocd-lab-demo-app
        # Only treat semver tags as eligible Freight.
        semverConstraint: ">=0.0.0"
        discoveryLimit: 20


